### ISSUE TITLE
Q: searchParams.String method behavior with empty value

### ISSUE THREAD

**Issue by miron6** [nlnwa/whatwg-url#13]
Hello!

Such code
```go
url, _ := url.Parse("http://test.com/path?aname=test&bname=foo")
url.SearchParams().Set("aname", "")
fmt.Println(url.String())
```
outputs the result
```
http://test.com/path?aname&bname=foo
```

Whatwg [urlencoded-serializing](https://url.spec.whatwg.org/#urlencoded-serializing) standard looks like `=` should still be, even if value is empty.

Am I missing something?

**Comment by maeb** [comment]
Thank you for the report. We will look into this. The code is here https://github.com/nlnwa/whatwg-url/blob/f9c8322be884c31b6e3678f9661dcda6e8193e8d/url/searchparams.go#L154-L157

**Comment by johnerikhalse** [comment]
Fixed behavior to be in line with spec. Added an option to get the old behavior. This was needed for the Google safe browsing canonicalization and might be useful for others as well.
