### ISSUE TITLE
Tests fail on 32-bit architectures

### ISSUE THREAD

**Issue by steev** [nlnwa/whatwg-url#21]
Hi, Steev with Kali Linux here.  We have packaged up your repository, and while running it through our CI, the tests fail on all 32-bit architectures (armhf, armel, i386). 

[i386 log](https://gitlab.com/kalilinux/packages/golang-github-nlnwa-whatwg-url/-/jobs/6887608667)

[armhf log](https://gitlab.com/kalilinux/packages/golang-github-nlnwa-whatwg-url/-/jobs/6887608534)

[armel log](https://gitlab.com/kalilinux/packages/golang-github-nlnwa-whatwg-url/-/jobs/6887608630)

I am not sure if this is intended and this library is only supposed to be used on 64-bit architectures, but I didn't see anyone else opening any issues and I wanted to make you aware that it wasn't working in case this isn't the case.

**Comment by trym-b** [comment]
Hi Steev

Thank you for opening this issue. After taking a brief look at this repository, I also struggle to figure out what our supported architectures and/or operating systems are.

FYI @maeb

**Comment by steev** [comment]
Thank you so much for the quick patch and looking into this! Sorry we didn't report it sooner!
